### ISSUE TITLE
'Couldn't find any package by regex'

### ISSUE THREAD

**Issue by Cyken-Zeraux** [paragonie/airship-docs#1]
Though the machine says, ubuntu, its actually Debian 8.3 x64 with DigitalOcean. I tried to do this under ubuntu, but that also didn't work.
https://gist.github.com/Cyken-Zeraux/aecf0e3a9b30e2ae40968781c371e450
Following the 'https://github.com/paragonie/airship-docs/blob/master/en-us/01-intro/2-Installing.md' guide.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/airship-docs/commit/97cb9578dc80787d7e8731f510e67571f661f67d

Does that help?

**Comment by Cyken-Zeraux** [comment]
Yep, that gets PHP installed, however same issue with Postgre. 'deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main' is not a command, its supposed to be put into the sources list, but its listed as if its a command.

When that is added to the sources list, this error occurs on apt-get update
`W: GPG error: http://apt.postgresql.org jessie-pgdg InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7FCC7D46ACCC4CF8
`

**Comment by paragonie-scott** [comment]
Okay, this should be fixed with https://github.com/paragonie/airship-docs/commit/15e0350007d1294875ed7b2ec04fe01174634c66

Thank you for the feedback. :)
