### ISSUE TITLE
Documentation claims you should install v0.3.0

### ISSUE THREAD

**Issue by co60ca** [paragonie/airship-docs#2]
https://github.com/paragonie/airship-docs/blob/master/en-us/01-intro/2-Installing.md

```
cd /var/www/
git clone https://github.com/paragonie/airship.git
git checkout v0.3.0
cd airship
composer install
```

Says beta only, did I miss the suggested install method? Or is this the same + v1.0.2 now?

**Comment by paragonie-security** [comment]
The documentation is out of date

**Comment by co60ca** [comment]
I apologize, I've been struggling with the install myself due to permissions errors most likely, will be giving it another crack tomorrow.

**Comment by paragonie-scott** [comment]
It's all good. Does this help? https://github.com/paragonie/airship-docs/commit/810ed517958ab14c57cd3dcd65d246ca10e0bb30

**Comment by co60ca** [comment]
Yup
