### ISSUE TITLE
Default GPG keyserver change

### ISSUE THREAD

**Issue by colinmo** [paragonie/airship-docs#3]
I found that to install PHP7 I had to change GPG library path as per http://jotham-city.com/blog/2015/02/14/verifying-gpg-signatures-for-makepkg/

Not so much a bug, as a suggested edit if people find an issue.

**Comment by paragonie-scott** [comment]
Thanks, I'll fix this as soon as I can. I consider anything that trips people up to be a documentation bug. :)
