### ISSUE TITLE
Docker image not available anymore

### ISSUE THREAD

**Issue by LukasReschke** [paragonie/airship-docs#5]
The docker image linked from https://github.com/paragonie/airship-docs/blob/578d4f384268d19fd915c53cff9500632dd1b74d/en-us/01-intro/2-Installing.md is resulting in a 404:

https://hub.docker.com/r/co60ca/airship/

**Comment by paragonie-scott** [comment]
Hmm, I think @co60ca might've taken it down. I'll see about setting up a dedicated replacement once the Dockerfile enhancements are ready.

**Comment by co60ca** [comment]
@LukasReschke I was 100% sure I made a pull request to address this but it didn't take. Since we use docker-compose now there isn't a once press docker.

**Comment by co60ca** [comment]
@LukasReschke Oh hey I found it @paragonie-scott 
https://github.com/paragonie/airship-docs/pull/6

**Comment by co60ca** [comment]
```
git clone https://github.com/paragonie/airship.git
cd airship
docker-compose up
```

If your docker is setup only to use root you may need `sudo docker-compose up`
Will probably work but I'm new with docker-compose and don't wanna to give people explicit instructions if they are wrong.
You will need of course, [docker-compose](https://docs.docker.com/compose/install/) and docker installed and running. But other than that it should install and start automatically.

We then utilize port 8080 on the host for the application.

**Comment by LukasReschke** [comment]
That either fails because the Dockerfile does something wrong or because there is an issue in master:

```
[Thu Jul 07 19:10:50.282350 2016] [:error] [pid 7] [client 172.18.0.1:35562] PHP Fatal error:  Uncaught Twig_Error_Loader: The "/var/www/airship/src/Cabin//Lens" directory does not exist. in /var/www/airship/vendor/twig/twig/lib/Twig/Loader/Filesystem.php:94\nStack trace:\n#0 /var/www/airship/vendor/twig/twig/lib/Twig/Loader/Filesystem.php(76): Twig_Loader_Filesystem->addPath('/var/www/airshi...', '__main__')\n#1 /var/www/airship/vendor/twig/twig/lib/Twig/Loader/Filesystem.php(34): Twig_Loader_Filesystem->setPaths(Array)\n#2 /var/www/airship/src/bootstrap.php(92): Twig_Loader_Filesystem->__construct('/var/www/airshi...')\n#3 /var/www/airship/src/public/index.php(86): require_once('/var/www/airshi...')\n#4 {main}\n  thrown in /var/www/airship/vendor/twig/twig/lib/Twig/Loader/Filesystem.php on line 94, referer: http://localhost:8080/
```

🙈

**Comment by co60ca** [comment]
Where is that failing?

**Comment by LukasReschke** [comment]
After you enter your admin credentials in the installer, you simply get a white page and this in the Apache error log.

**Comment by co60ca** [comment]
I got that too, it might be upstream, I haven't been following the project very closely and it's moving very fast, probably something to do with @paragonie-scott's new bad password stuff.

**Comment by paragonie-scott** [comment]
Yep, it's a bug. Haven't tagged v1.2.0 yet, and I'm glad I haven't.

**Comment by paragonie-scott** [comment]
The bug is, I suspect, that the cabin configuration isn't succeeding. You elected for a fast install, correct?

**Comment by co60ca** [comment]
Its upstream issue now.

If you checkout `git checkout v1.1.4` you can use the old Dockerfile method which bulks in the database with the application, which has since been changed.

**Comment by paragonie-scott** [comment]
I suspect the latest commit will fix it. The chown and chmod commands in the dockerfiles should already have fixed this :(

**Comment by co60ca** [comment]
From the error it looks like $active['name'] isn't set in bootstrap, should it be?

**Comment by paragonie-scott** [comment]
Yes, it should be.

**Comment by paragonie-scott** [comment]
https://github.com/paragonie/airship/commit/e618546449862407b976e119faa290be83da7a9d

**Comment by paragonie-scott** [comment]
We're discussing these issues in https://github.com/paragonie/airship/issues/104 -- once that's closed, this should be resolved too.

Thanks @LukasReschke for bringing this to our attention.
